/* Generated by re2c 0.13.5 on Mon Feb  4 00:03:07 2013 */
#line 3 "Zend/zend_language_scanner_defs.h"

enum YYCONDTYPE {
	yycST_IN_SCRIPTING,
	yycST_LOOKING_FOR_PROPERTY,
	yycST_BACKQUOTE,
	yycST_DOUBLE_QUOTES,
	yycST_HEREDOC,
	yycST_LOOKING_FOR_VARNAME,
	yycST_VAR_OFFSET,
	yycINITIAL,
	yycST_END_HEREDOC,
	yycST_NOWDOC,
};
